added malloc3.c to branch next
Beatman10/dmainc2nd pull request #3
Opened 2023-06-09 11:32 UTC by Atman1008

2023-06-09 12:16 UTC, EIC-JayGanatra requested changes

2023-06-09 12:16 UTC, EIC-JayGanatra commented on malloc3.c
> +    free(numbers);
While freeing the memory please keep the practice to check if it is NULL or not. if it is not NULL then free it, followed by assigning NULL to it.

2023-06-12 09:02 UTC, merged

2023-06-12 09:03 UTC, Beatman10 commented
issue resolved

2023-06-12 09:31 UTC, Beatman10 commented on malloc3.c
> +    free(numbers);
okay